name: deploy
on:
  push:
    paths:
      - 'serverless.yml'
      - 'kaskadi-webhooks-stock-lambda.js'
jobs:
  serverless:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
    - name: serverless-deploy
      uses: kaskadi/action-slscli@master
      with:
        command: 'deploy -v'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_SECRET }}
        SLS_DEPLOY_BUCKET: ${{ secrets.SLS_DEPLOY_BUCKET }}
        ES_ACCESS_ID: ${{ secrets.ES_ACCESS_ID }}
        ES_ACCESS_SECRET: ${{ secrets.ES_ACCESS_SECRET }}
